netbackupkops:
  containers:
    manager:
      image: asia-southeast2-docker.pkg.dev/joey-prod-project/prod-veritas/netbackupkops:10.4.0.1
      resources:
        limits:
          cpu: 150m
          memory: 600Mi
        requests:
          cpu: 100m
          memory: 500Mi
  kopsPvcStorageClass:
  kopsPvcSize: 10Gi
  pvMountPath: /usr/openv
  imagePullSecrets: 
  - name: gcr-json-key
  fipsMode: DISABLE
  acceleratorTracklogPvcStorageClass: None
nbsetup:
  replicas: 1
  containers:
    netbackup_config_pod:
      nbprimaryserver: prod-id-adp-nbumaster-instance-01
      nbsha256fingerprint: 3F:83:2C:86:06:44:F7:50:75:CF:FD:4A:03:16:75:90:0F:B2:76:F7:6E:AE:87:A6:EB:6F:04:7D:64:BD:45:03
      k8sCluster: 34.101.178.17
      k8sPort: 443
      datamoverimage: asia-southeast2-docker.pkg.dev/joey-prod-project/asia-southeast2/prod-veritas/netbackupdatamover:10.4.0.1
      logLevel: INFO
      storageclassblock: standard-rwo
      volumesnapshotclassblock: standard-rwo-vsc
      storageclassfilesystem: standard-rwo
      volumesnapshotclassfilesystem: standard-rwo-vsc
