netbackupkops:
  containers:
    manager:
      image: asia-southeast2-docker.pkg.dev/joey-dev-project/dev-veritas/netbackupkops:netbackupkops_10.4_0018
      resources:
        limits:
          cpu: 150m
          memory: 600Mi
        requests:
          cpu: 100m
          memory: 500Mi
  kopsPvcStorageClass:
  kopsPvcSize: 10Gi
  pvMountPath: /usr/openv
  imagePullSecrets: 
  - name: netbackupkops-docker-creds
  fipsMode: DISABLE
  acceleratorTracklogPvcStorageClass: None
nbsetup:
  replicas: 1
  containers:
    netbackup_config_pod:
      nbprimaryserver: sta-id-adp-nbumaster-instance-01
      nbsha256fingerprint: 31:0B:AA:55:43:2A:0A:9F:76:72:06:75:FE:BB:98:DA:E1:BF:7D:AD:D4:62:B0:DF:52:B6:19:E7:F0:17:7D:81
      k8sCluster: 10.131.6.2
      k8sPort: 443
      datamoverimage: asia-southeast2-docker.pkg.dev/joey-dev-project/dev-veritas/netbackupdatamover:dev-10.4
      logLevel: INFO
      storageclassblock: standard-rwo
      volumesnapshotclassblock: standard-rwo-vsc
      storageclassfilesystem: standard-rwo
      volumesnapshotclassfilesystem: standard-rwo-vsc
