netbackupkops:
  containers:
    manager:
      image: rezaseptiyanputra/nbukops:10.4.0.1
      resources:
        limits:
          cpu: 150m
          memory: 600Mi
        requests:
          cpu: 100m
          memory: 500Mi
  kopsPvcStorageClass:
  kopsPvcSize: 10Gi
  pvMountPath: /usr/openv
  imagePullSecrets: 
  - name: netbackupkops-docker-cred
  fipsMode: DISABLE
  acceleratorTracklogPvcStorageClass: None
nbsetup:
  replicas: 1
  containers:
    netbackup_config_pod:
      nbprimaryserver: sta-id-adp-nbumaster-instance-01
      nbsha256fingerprint: 82:FB:3A:4D:C4:8E:93:E8:00:4F:68:40:EF:CF:34:80:E9:4B:65:0A:74:B1:57:0F:78:88:31:A9:7A:B2:33:72
      k8sCluster: 34.101.124.204
      k8sPort: 443
      datamoverimage: rezaseptiyanputra/nbudata-mover:10.4.0.1
      logLevel: INFO
      storageclassblock: standard-rwo
      volumesnapshotclassblock: standard-rwo-vsc
      storageclassfilesystem: standard-rwo
      volumesnapshotclassfilesystem: standard-rwo-vsc
