apiVersion: netbackup.veritas.com/v1
kind: BackupServerCert
metadata:
  name: nbudatamovercertificate
  namespace: netbackup
spec:
  clusterName: 34.101.124.204
  backupServer: sta-id-adp-nbumaster-instance-01
  certificateOperation: Create
  certificateType: NBCA
  nbcaAttributes:
    nbcaCreateOptions:
      secretName: netbackupkops-backupservercert-secret
