apiVersion: netbackup.veritas.com/v1
kind: BackupServerCert
metadata:
  name: nbudatamovercertificate
  namespace: netbackup
spec:
  clusterName: 10.131.6.2
  backupServer: sta-id-adp-nbumaster-instance-01
  certificateOperation: Create
  certificateType: NBCA
  nbcaAttributes:
    nbcaCreateOptions:
      secretName: netbackupkops-backupservercert-secret
