kind: ConfigMap 
apiVersion: v1 
metadata:
  name: sta-id-adp-nbumaster-instance-01
  namespace: netbackup
data:
  datamover.hostaliases: |
        10.141.141.2=sta-id-adp-nbumaster-instance-01
        10.141.141.4=sta-id-adp-nbumedia-instance-01
  datamover.properties: |
        image=rezaseptiyanputra/nbudata-mover:10.4.0.1
        imagePullSecret=netbackupkops-docker-cred
  version: "1"
