kind: ConfigMap 
apiVersion: v1 
metadata:
  name: prdnbumaster02
  namespace: netbackupkops
data:
  datamover.hostaliases: |
        172.18.0.6=prdnbumaster02
        172.18.0.7=prdnbumedia02
  datamover.properties: |
        image=rezaseptiyanputra/nbudata-mover:10.4.0.1
        imagePullSecret=netbackupkops-docker-cred
  version: "1"
