apiVersion: v1
kind: Secret
metadata:
  name: netbackupkops-backupservercert-secret
  namespace: netbackup
type: Opaque
stringData:
  token: ILXQBOMJPSTGAWFR
  fingerprint: 31:0B:AA:55:43:2A:0A:9F:76:72:06:75:FE:BB:98:DA:E1:BF:7D:AD:D4:62:B0:DF:52:B6:19:E7:F0:17:7D:81